#cloud-config
coreos:
  update:
    reboot-strategy: off
  units:
    - name: update-engine.service
      command: stop
    - name: iptables-restore.service
      enable: true
      command: start
write_files:
  - path: /etc/sysctl.d/nf.conf
    permissions: 0644
    owner: root:root
    content: |
      net.ipv4.ip_forward=1
  - path: /var/lib/iptables/rules-save
    permissions: 0644
    owner: root:root
    content: |
      *nat
      -A POSTROUTING -o ens4v1 -j MASQUERADE
      COMMIT
